owner: FlexURL-link
repo: status.flexurl.link

sites:
  - name: flexurl.link
    url: https://flexurl.link
    icon: https://img.drayko.xyz/flexurl-logo.png
  - name: create.flexurl.link
    url: https://create.flexurl.link
    icon: https://img.drayko.xyz/flexurl-logo.png

status-website:
  cname: status.flexurl.link
  logoUrl: https://img.drayko.xyz/flexurl-logo.svg
  name: FlexURL
  favicon: https://img.drayko.xyz/flexurl-favicon.png
  faviconSvg: https://img.drayko.xyz/flexurl-favicon.svg

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/30 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
